source 'https://rubygems.org'

gem 'rails', '~> 3.2.18'
gem 'sqlite3'
gem 'rflow', '>= 1.0.1'
gem 'rflow-components-http'
gem 'jquery-rails'
gem 'therubyracer'
gem 'rspec-rails'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end
